## Конвейер очистки и предобработки данных 

В данном блокноте реализован поэтапный процесс очистки сырых данных подкастов. Все функции импортируются из модуля `src/cleaning.py`

### Этап 1: Загрузка исходных данных
Загружаем сырой датасет из CSV-файла и фиксируем начальное количество строк.

In [ ]:
import sys
from pathlib import Path

import pandas as pd

from src.cleaning import *

df = load_data()
before_rows = len(df)
print(f"Данные загружены. Исходное количество строк (до): {before_rows}")
print("Список столбцов:", df.columns.tolist())

Данные загружены. Исходное количество строк (до): 199999
Список столбцов: ['date', 'rank', 'region', 'chartRankMove', 'episodeUri', 'showUri', 'episodeName', 'description', 'show.name', 'show.publisher', 'duration_ms', 'explicit', 'languages', 'release_date', 'show.media_type', 'show.total_episodes']

### Этап 2: Приведение имён столбцов к единому виду
Перевод в нижний регистр, замена пробелов и точек на подчёркивания, удаление служебных символов.

In [3]:
rows_before = len(df)
df = clean_column_names(df)
rows_after = len(df)

print(f"Строк до: {rows_before} | Строк после: {rows_after}")
print("Новые имена столбцов:", df.columns.tolist())

2_clean_column_names | processed=199999 | changed=8 | removed=0
Строк до: 199999 | Строк после: 199999
Новые имена столбцов: ['date', 'rank', 'region', 'chart_rank_move', 'episode_uri', 'show_uri', 'episode_name', 'description', 'show_name', 'show_publisher', 'duration_ms', 'explicit', 'languages', 'release_date', 'show_media_type', 'show_total_episodes']

### Этап 3: Явное приведение типов
Преобразование столбцов с датами в datetime, числовых — в числовые типы (`Int32`, `Float`), а строковых — в тип `string`.

In [4]:
rows_before = len(df)
df = convert_types(df)
rows_after = len(df)

print(f"Строк до: {rows_before} | Строк после: {rows_after} (Типы данных успешно приведены)")

convert_types | processed=199999 | changed=0 | removed=0
Строк до: 199999 | Строк после: 199999 (Типы данных успешно приведены)

### Этап 4: Выявление скрытых пропусков
Поиск текстовых артефактов (`"n/a"`, `"-"`, `"unknown"`, `"нет данных"`), а также нулей и невозможных дат с переводом их в стандартный пропуск `pd.NA`.

In [5]:
rows_before = len(df)
df = replace_hidden_missing(df)
rows_after = len(df)

print(f"Строк до: {rows_before} | Строк после: {rows_after} (Скрытые пропуски обработаны)")

replace_hidden_missing | processed=199999 | changed=28 | removed=0
Строк до: 199999 | Строк после: 199999 (Скрытые пропуски обработаны)

### Этап 5: Анализ структуры пропусков
Оценка доли пропущенных значений по каждому столбцу и в разрезе регионов.

In [6]:
missing, by_region = analyze_missing(df)

print(" Доля пропусков по столбцам ")
display(missing)

print(" Доля пропусков по регионам ")
display(by_region)

analyze_missing | processed=199999 | changed=0 | removed=0
 Доля пропусков по столбцам

                     count  percent
date                     0     0.00
rank                     0     0.00
region                   0     0.00
chart_rank_move          0     0.00
episode_uri              0     0.00
show_uri                 0     0.00
episode_name             0     0.00
description           2332     1.17
show_name                0     0.00
show_publisher           0     0.00
duration_ms              0     0.00
explicit                 0     0.00
languages                0     0.00
release_date             0     0.00
show_media_type          0     0.00
show_total_episodes      0     0.00

 Доля пропусков по регионам

region
co    0.003355
cl    0.002442
ar    0.001717
in    0.001696
pl    0.001311
at    0.001203
id    0.001067
ph    0.000726
br    0.000616
de    0.000594
mx    0.000570
es    0.000548
it    0.000370
jp    0.000311
fr    0.000159
gb    0.000111
ie    0.000074
nz    0.000059
us    0.000037
nl    0.000015
ca    0.000014
au    0.000014
dtype: float64

### Этап 6: Удаление дубликатов
Удаление полных дубликатов и дубликатов по составному ключу (`date`, `episode_uri`, `region`) с сохранением последней записи (`keep="last"`).

In [7]:
rows_before = len(df)
df = remove_duplicates(df)
rows_after = len(df)

removed_count = rows_before - rows_after
print(f"Строк до: {rows_before} | Строк после: {rows_after} | Удалено дубликатов: {removed_count}")

remove_duplicates | processed=199999 | changed=0 | removed=0
Строк до: 199999 | Строк после: 199999 | Удалено дубликатов: 0

### Этап 7: Нормализация категориальных столбцов
Приведение регистра, удаление пробелов, унификация значений и объединение редких категорий (с частотой меньше `min_count`) в группу `"other"`.

In [8]:
rows_before = len(df)
df = normalize_categories(df, min_count=10)
rows_after = len(df)

print(f"Строк до: {rows_before} | Строк после: {rows_after} (Категории нормализованы)")

normalize_categories | processed=199999 | changed=237720 | removed=0
Строк до: 199999 | Строк после: 199999 (Категории нормализованы)

### Этап 8: Обработка текстовых столбцов
Очистка описаний (`description`) от HTML-разметки, лишних пробелов и служебных пустых значений.

In [9]:
rows_before = len(df)
df = clean_text(df, col="description")
rows_after = len(df)

print(f"Строк до: {rows_before} | Строк после: {rows_after} (Текст очищен)")

clean_text | processed=199999 | changed=86241 | removed=0
Строк до: 199999 | Строк после: 199999 (Текст очищен)

### Этап 9: Нормализация числовых единиц
Проверка единиц измерения (длительность в миллисекундах учтена корректно).

In [10]:
rows_before = len(df)
df = normalize_numeric_units(df)
rows_after = len(df)

print(f"Строк до: {rows_before} | Строк после: {rows_after} (Единицы проверены)")

Строк до: 199999 | Строк после: 199999 (Единицы проверены)

### Этап 10: Проверка предметных ограничений
Удаление строк с нарушением логических правил: отрицательные ранги/длительности, даты из будущего, некорректный диапазон `release_date > date`.

In [11]:
rows_before = len(df)
df = check_constraints(df)
rows_after = len(df)

removed_count = rows_before - rows_after
print(f"Строк до: {rows_before} | Строк после: {rows_after} | Удалено невалидных строк: {removed_count}")

check_constraints | processed=199999 | changed=0 | removed=1
Строк до: 199999 | Строк после: 199998 | Удалено невалидных строк: 1

### Этап 11: Выявление выбросов
Анализ числовых метрик (`duration_ms`, `show_total_episodes`) двумя независимыми методами: межквартильный размах (IQR) и Z-оценка.

In [12]:
outliers_df = detect_outliers(df)
print("Отчет по выбросам (IQR vs Z-score)")
display(outliers_df)

detect_outliers | processed=199998 | changed=0 | removed=0
Отчет по выбросам (IQR vs Z-score)

                column    iqr  zscore  both
0          duration_ms  10181    2346  2346
1  show_total_episodes  16879    4546  4546

### Этап 12: Сохранение результатов и итоговый отчёт
Сохранение очищенного набора в формат `.parquet` и расчет общего процента потерянных данных.

In [13]:
save_clean_data(df)

after_rows = len(df)
lost_count = before_rows - after_rows
lost_pct = (lost_count / before_rows) * 100

print("\n" + "="*50)
print(" ИТОГОВЫЙ ОТЧЁТ ОЧИСТКИ ДАННЫХ:")
print(f"Исходное число строк (Было):  {before_rows}")
print(f"Итоговое число строк (Стало): {after_rows}")
print(f"Потеряно строк: {lost_count} ({lost_pct:.2f}%)")
print("="*50)

if lost_pct > 10:
    print("ВНИМАНИЕ: Потеря данных превысила 10%. См. обоснование ниже.")
else:
    print("Потеря данных в пределах нормы (< 10%).")

save_clean_data | processed=199998 | changed=0 | removed=0
Сохранено: E:\project\data\processed\clean.parquet

==================================================
 ИТОГОВЫЙ ОТЧЁТ ОЧИСТКИ ДАННЫХ:
Исходное число строк (Было):  199999
Итоговое число строк (Стало): 199998
Потеряно строк: 1 (0.00%)
==================================================
Потеря данных в пределах нормы (< 10%).

###  Проверка согласованности (Consistency)
**Цель:** Убедиться, что датасет, полученный интерактивным выполнением блокнота, и датасет, полученный запуском модуля через командную строку (`python -m src.pipeline`), полностью идентичны построчно.

**Способ проверки:** Мы сохраняем результат из блокнота в `clean.parquet`, а затем сравниваем его с `clean_cli.parquet` через функцию `pd.testing.assert_frame_equal`.

In [ ]:
from pathlib import Path

import pandas as pd

df_notebook = pd.read_parquet("../data/processed/clean.parquet")
df_cli = pd.read_parquet("../data/processed/clean_cli.parquet")

try:
    pd.testing.assert_frame_equal(df_notebook, df_cli, check_like=False)
    
    print("Наборы данных, полученные из блокнота и CLI, полностью идентичны построчно.")
except AssertionError as e:
    print("Обнаружены расхождения между блокнотом и CLI:")
    print(e)

Наборы данных, полученные из блокнота и CLI, полностью идентичны построчно.

### Проверка идемпотентности
**Цель:** Доказать, что повторный запуск пайплайна на тех же исходных данных дает абсолютно идентичный результат и не ломает структуру данных.
**Как проверить:** Повторный запуск скрипта `python -m src.pipeline --mode full` перезаписывает файл `clean.parquet`, но его контрольные суммы и содержимое остаются неизменными.

### Проверка воспроизводимости 
**Цель:** Убедиться, что всю цепочку обработки можно восстановить с нуля одной командой, не затрагивая исходный каталог `raw`.

**Как проверить:** Очистить папки `interim` и `processed` одной командой в терминале и заново запустить пайплайн.

**Команда**: Remove-Item -Recurse -Force data/interim/* , data/processed/*; python -m src.pipeline --mode full